### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by flex36ty** [INUI-Dev/WHMCS-Smarters-IPTV-Nulled#3]
This nulled version works for 2 days and stopped working. I asked him to fix it or give my money back and no reply. Don't buy this.

**Comment by flex36ty** [comment]
I sent you screenshots after screenshots proving that the license status showed nothing at all and it worked with a legit trial. No reply at all

**Comment by LiamKenyon** [comment]
I sent you 4 replies and even offered to take a look at your setup for you, can provide these as evidence if you'd like?

No other customer has reported any faults.
